# -*- coding: utf-8 -*-
"""01_DATA_PREPROCESSING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dLomor0jk2kIstbsqLP8reVIZjNX1KHe

**Section 1: Import Libraries**
"""

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

"""**Section 2: Load Dataset**"""

df = pd.read_csv("smart_accessibility_analytics_dataset.csv")

df.head()

"""**Section 3: Basic Information**"""

print("Shape :", df.shape)

df.info()

"""**Section 4: Statistical Summary**"""

df.describe(include="all").T

"""**Section 5: Missing Values**"""

#
missing = df.isnull().sum()
missing = missing[missing > 0]
missing

# Percentage
missing_percentage = (df.isnull().sum()/len(df))*100
missing_percentage.sort_values(ascending=False)

# Visualization
plt.figure(figsize=(12,5))
sns.heatmap(df.isnull(), cbar=False)
plt.title("Missing Values")
plt.show()

"""**Section 6: Duplicate Records**"""

duplicates = df.duplicated().sum()

print("Duplicate Rows :", duplicates)

"""**Data Type Validation**"""

df.dtypes

"""**Unique Values**"""

for column in df.columns:
    print(column)
    print(df[column].unique())
    print("----------------")

"""**Data Consistency Checks**"""

df[df["Accessibility_Score"]>100]

"""**Outlier Detection**"""

numerical_columns = df.select_dtypes(include=np.number).columns

"""**Handle Missing Values**"""

df[numerical_columns] = df[numerical_columns].fillna(df[numerical_columns].median())

categorical_columns = df.select_dtypes(include="object").columns

for col in categorical_columns:

    df[col] = df[col].fillna(df[col].mode()[0])

"""**Encode Categorical Variables**"""

label_encoder = LabelEncoder()

for col in categorical_columns:
    if col not in ["Location_ID", "Location_Name", "Accessibility_Category", "Improvement_Priority"]:
        df[col] = label_encoder.fit_transform(df[col])

"""**Feature Scaling**"""

scaler = StandardScaler()

scaled_features = scaler.fit_transform(df[numerical_columns])

scaled_df = pd.DataFrame(
    scaled_features,
    columns=numerical_columns
)

"""**Final Dataset**"""

print(df.shape)
df.head()

"""**Save Clean Dataset**"""

df.to_csv(
    "cleaned_accessibility_dataset.csv",
    index=False
)