# -*- coding: utf-8 -*-
"""02_Exploratory_Data_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1inFPK8eNayOvxaWd1ZGyRhQbqiVORsCa

**SECTION 01 IMPORT LIBRARIES**
"""

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("ggplot")

"""**SECTION 02 LOAD DATASET**"""

df = pd.read_csv("cleaned_accessibility_dataset.csv")
df.head()

"""**SECTION 03 DATASET OVERVIEW**"""

print("="*50)
print("DATASET SHAPE")
print("="*50)
print(df.shape)

print("\n")

print("="*50)
print("DATA TYPES")
print("="*50)
print(df.dtypes)

print("\n")

print("="*50)
print("MISSING VALUES")
print("="*50)
print(df.isnull().sum())

print("\n")

print("="*50)
print("DUPLICATES")
print("="*50)
print(df.duplicated().sum())

"""**SECTION 04 STATISTICAL SUMMARY**"""

df.describe().T

df.describe(include = "object").T

"""**SECTION 05 ACCESSIBILITY SCORE DISTRIBUTION**"""

plt.figure(figsize=(10,6))

sns.histplot(df["Accessibility_Score"], bins=20, kde=True)

plt.title("Accessibility Score Distribution")
plt.xlabel("Accessibility Score")
plt.ylabel("Frequency")
plt.show()

"""**SECTION 06 ACCESSIBILITY CATEGORY**"""

plt.figure(figsize=(8,5))

sns.countplot(x="Accessibility_Category", data=df)
plt.title("Accessibility Category")
plt.show()

"""**SECTION 07 LOCATION TYPE DISTRIBUTION**"""

plt.figure(figsize=(12,5))

sns.countplot(y="Location_Type", data=df)
plt.title("Distribution of Location Types")
plt.show()

"""**SECTION 08 CROWD LEVEL**"""

plt.figure(figsize=(7,5))

sns.countplot(x="Crowd_Level", data=df)
plt.title("Crowd Level Distribution")
plt.show()

"""**SECTION 09 SAFETY LEVEL**"""

plt.figure(figsize=(7,5))

sns.countplot(x="Safety_Level", data=df)
plt.title("Safety Level Distribution")
plt.show()

"""**SECTION 10 LIGHTING**"""

plt.figure(figsize=(7,5))

sns.countplot(x="Lighting", data=df)
plt.title("Lighting Distribution")
plt.show()

"""**SECTION 11 USER RATING**"""

plt.figure(figsize=(8,5))

sns.histplot(df["User_Rating"], bins=10, kde=True)
plt.title("User Rating Distribution")
plt.show()

"""**SECTION 12 COMPLAINTS**"""

plt.figure(figsize=(8,5))

sns.histplot(df["Accessibility_Complaints"], bins=20)
plt.title("Accessibility Complaints")
plt.show()

"""**SECTION 13 ACCESSIBILITY SCORE BY LOCATION TYPE**"""

plt.figure(figsize=(14,6))

sns.boxplot(
    x="Location_Type",
    y="Accessibility_Score",
    data=df
)

plt.xticks(rotation=45)
plt.title("Accessibility Score by Location Type")
plt.show()

"""**SECTION 14 ACCESSIBILITY SCORE VS CROWD LEVEL**"""

plt.figure(figsize=(8,5))

sns.boxplot(
    x="Crowd_Level",
    y="Accessibility_Score",
    data=df
)
plt.title("Accessibility Score vs Crowd Level")
plt.show()

"""**SECTION 15 ACCESSIBILITY SCORE VS SAFETY**"""

plt.figure(figsize=(8,5))

sns.boxplot(
    x="Safety_Level",
    y="Accessibility_Score",
    data=df
)
plt.title("Accessibility Score vs Safety")
plt.show()

"""**SECTION 16 ACCESSIBILITY SCORE VS USER RATING**"""

plt.figure(figsize=(8,5))

sns.scatterplot(
    x="User_Rating",
    y="Accessibility_Score",
    data=df
)
plt.title("Accessibility Score vs User Rating")
plt.show()

"""**SECTION 17 CORRELATION HEATMAP**"""

numerical_df = df.select_dtypes(include=np.number)
plt.figure(figsize=(18,12))

sns.heatmap(
    numerical_df.corr(),
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)
plt.title("Correlation Heatmap")
plt.show()

"""**SECTION 18 PAIR PLOT**"""

selected = df[
    [
        "Accessibility_Score",
        "User_Rating",
        "Accessibility_Complaints",
        "Average_Waiting_Time",
        "Daily_Footfall"
    ]
]

sns.pairplot(selected)
plt.show()

"""**SECTION 19 NUMERICAL FEATURES DISTRIBUTION**"""

numerical_columns = df.select_dtypes(include=np.number).columns

df[numerical_columns].hist(
    figsize=(18,18),
    bins=20
)
plt.tight_layout()
plt.show()

"""**SECTION 20 FINAL INSIGHT**

1. Most public locations have good accessibility scores.
2. Hospitals and malls generally have higher accessibility than older government buildings.
3. Higher crowd levels are associated with lower accessibility scores.
4. Better safety and lighting correspond to higher user ratings.
5. Accessibility complaints increase as accessibility scores decrease.
6. Strong correlations exist between accessibility features and the accessibility score.
"""

df.info()

df.head()

"""# **EXTRA**

**Add a Correlation with Target**
"""

corr = numerical_df.corr()["Accessibility_Score"].sort_values(ascending=False)

plt.figure(figsize=(8,10))
sns.barplot(
    x=corr.values,
    y=corr.index
)

plt.title("Correlation with Accessibility Score")
plt.show()

"""**Accessibility Category Pie Chart**"""

df["Accessibility_Category"].value_counts().plot(
    kind="pie",
    autopct="%1.1f%%",
    figsize=(6,6)
)

plt.ylabel("")
plt.title("Accessibility Category Distribution")
plt.show()