# -*- coding: utf-8 -*-
"""03_Feature_Engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Aq9-Sc6KD8pbgJ9xYgX797UNuwOuqdpk

**STEP 01 IMPORT LIBRARIES**
"""

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

"""**STEP 02 LOAD DATASET**"""

df = pd.read_csv("cleaned_accessibility_dataset.csv")
df.head()

"""**STEP 03 CHECK COLUMNS**"""

print(df.columns.tolist())

"""# ** STEP 4CREATE NEW FEATURES**

**1. INFRASTRUCTURE SCORE**
"""

infrastructure_features = [
    "Ramp_Available",
    "Elevator_Available",
    "Wheelchair_Entrance",
    "Accessible_Washroom",
    "Reserved_Parking"
]

df["Infrastructure_Score"] = df[infrastructure_features].sum(axis=1)

"""**2. ACCESSIBILITY SUPPORT SCORE**"""

support_features = [
    "Braille_Signage",
    "Audio_Announcements",
    "Tactile_Path"
]

df["Accessibility_Support_Score"] = df[support_features].sum(axis=1)

"""**3. SAFETY INDEX**"""

safety_features = [
    "Lighting",
    "Safety_Level",
    "CCTV_Available"
]
df["Safety_Index"] = df[safety_features].sum(axis=1)

"""**4. FACILITY SCORE**"""

facility_features = [
    "Parking_Available",
    "Public_Transport_Nearby"
]

df["Facility_Score"] = df[facility_features].sum(axis=1)

"""**5. CROWD RISK SCORE**"""

df["Crowd_Risk"] = (
    df["Crowd_Level"] *
    df["Average_Waiting_Time"]
)

"""**6. COMPLAINT RATE**"""

df["Complaint_Rate"] = (
    df["Accessibility_Complaints"] /
    (df["Daily_Footfall"] + 1)
)

"""**7. ACCESSIBILITY EFFICIENCY**"""

df["Accessibility_Efficiency"] = (
    df["Accessibility_Score"] /
    (df["Average_Waiting_Time"] + 1)
)

"""**STEP 5 VERIFY NEW FEATURES**"""

new_features = [
    "Infrastructure_Score",
    "Accessibility_Support_Score",
    "Safety_Index",
    "Facility_Score",
    "Crowd_Risk",
    "Complaint_Rate",
    "Accessibility_Efficiency"
]

df[new_features].head()

"""**STEP 06 CORRELATION WITH TARGET**"""

corr = (
    df.corr(numeric_only=True)["Accessibility_Score"]
    .sort_values(ascending=False)
)

plt.figure(figsize=(8,10))

sns.barplot(
    x=corr.values,
    y=corr.index
)

plt.title("Correlation with Accessibility Score")

plt.show()

"""**SAVE ENGINEERED DATASET**"""

df.to_csv(
    "engineered_accessibility_dataset.csv",
    index=False
)