# -*- coding: utf-8 -*-
"""05_CLASSIFICATION_MODELS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tpGWQlDHjIQZvvmNmprmRrH8QujS8c5_

**STEP 01 IMPORT LIBRARIES**
"""

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

from sklearn.linear_model import LogisticRegression

from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier

from sklearn.svm import SVC

from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    precision_score,
    recall_score,
    f1_score,
    cohen_kappa_score,
    roc_auc_score
)

from sklearn.preprocessing import LabelEncoder

"""**STEP 02 LOAD DATASET**"""

df = pd.read_csv("engineered_accessibility_dataset.csv")

"""**STEP 3 ENCODE TARGET**"""

encoder = LabelEncoder()

df["Accessibility_Category"] = encoder.fit_transform(
    df["Accessibility_Category"]
)

"""**STEP 4 FEATURES & TARGET**"""

X = df.drop(columns=[
    "Accessibility_Score",
    "Accessibility_Category",
    "Improvement_Priority",
    "Location_ID",
    "Location_Name"
], errors="ignore")

y = df["Accessibility_Category"]

"""**STEP 5 TRAIN THE SPLIT**"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

"""**STEP 6 UNIVERSAL EVALUATION FUNCTION**"""

def evaluate_classifier(model, name):

  model.fit(X_train, y_train)

  prediction = model.predict(X_test)

  accuracy = accuracy_score(y_test, prediction)

  precision = precision_score(
      y_test,
      prediction,
      average="weighted"
  )

  recall = recall_score(
      y_test,
      prediction,
      average="weighted"
  )

  f1 = f1_score(
      y_test,
      prediction,
      average="weighted"
  )

  kappa = cohen_kappa_score(
      y_test,
      prediction
  )

  print("="*60)
  print(name)
  print("="*60)

  print("Accuracy :", round(accuracy,3))
  print("Precision :", round(precision,3))
  print("Recall :", round(recall,3))
  print("F1 Score :", round(f1,3))
  print("Kappa :", round(kappa,3))

  print("\nClassification Report\n")

  print(classification_report(y_test,prediction))

  cm = confusion_matrix(y_test,prediction)

  plt.figure(figsize=(6,5))

  sns.heatmap(
      cm,
      annot=True,
      fmt="d",
      cmap="Blues"
  )

  plt.title(name)

  plt.xlabel("Predicted")

  plt.ylabel("Actual")

  plt.show()

  return accuracy, precision, recall, f1, kappa

"""**STEP 7 LOGISTIC REGRESSION**"""

logistic = LogisticRegression(max_iter=1000)

evaluate_classifier(
    logistic,
    "Logistic Regression"
)

"""**STEP 8 DECISION TREE**"""

tree = DecisionTreeClassifier(
    random_state=42
)

evaluate_classifier(
    tree,
    "Decision Tree"
)

"""**STEP 9 RANDOM FOREST**"""

forest = RandomForestClassifier(
    random_state=42
)

evaluate_classifier(
    forest,
    "Random Forest"
)

"""**STEP 10 BAGGING**"""

bagging = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=100,
    random_state=42
)

evaluate_classifier(
    bagging,
    "Bagging"
)

"""**STEP 11 SVM**"""

svm = SVC(
    probability=True,
    random_state=42
)

evaluate_classifier(
    svm,
    "Support Vector Machine"
)

"""**STEP 12 XGBOOST**"""

xgb = XGBClassifier(
    random_state=42,
    eval_metric="mlogloss"
)

evaluate_classifier(
    xgb,
    "XGBoost"
)

"""**STEP 13 K-FOLD VALIDATION**"""

models = {

    "Logistic Regression": LogisticRegression(max_iter=1000),

    "Decision Tree": DecisionTreeClassifier(random_state=42),

    "Random Forest": RandomForestClassifier(random_state=42),

    "Bagging": BaggingClassifier(
        estimator=DecisionTreeClassifier(),
        random_state=42
    ),

    "SVM": SVC(),

    "XGBoost": XGBClassifier(
        eval_metric="mlogloss"
    )

}

for name, model in models.items():

    scores = cross_val_score(
        model,
        X,
        y,
        cv=5,
        scoring="accuracy"
    )

    print(name)

    print("Average Accuracy:",round(scores.mean(),3))

    print("-----------------------------")

"""**STEP 14 MODEL COMPARISION**"""

results = []

for name, model in models.items():

    model.fit(X_train,y_train)

    prediction = model.predict(X_test)

    results.append({

        "Model":name,

        "Accuracy":accuracy_score(y_test,prediction),

        "Precision":precision_score(
            y_test,
            prediction,
            average="weighted"
        ),

        "Recall":recall_score(
            y_test,
            prediction,
            average="weighted"
        ),

        "F1":f1_score(
            y_test,
            prediction,
            average="weighted"
        ),

        "Kappa":cohen_kappa_score(
            y_test,
            prediction
        )

    })

comparison = pd.DataFrame(results)

comparison.sort_values(
    by="Accuracy",
    ascending=False
)

"""**STEP 15 ACCURACY CHART**"""

plt.figure(figsize=(10,5))

sns.barplot(
    x="Model",
    y="Accuracy",
    data=comparison
)

plt.xticks(rotation=20)

plt.title("Classification Model Comparison")

plt.show()

"""**STEP 16 SAVE BEST MODEL**"""

import joblib
joblib.dump(
    forest,
    "best_classification_model.pkl"
)