# -*- coding: utf-8 -*-
"""06_Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-NxbibAaaOfmquemcahXAvX_EwpRANUr

**STEP 01 IMPORT LIBRARIES**
"""

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN
from sklearn.mixture import GaussianMixture
from sklearn.decomposition import PCA
from scipy.sparse.csgraph import minimum_spanning_tree
from scipy.spatial.distance import pdist
from scipy.spatial.distance import squareform

import networkx as nx

"""**STEP 02 LOAD DATASET**"""

df = pd.read_csv("engineered_accessibility_dataset.csv")

"""**STEP 03 SELECT FEATURES**"""

X = df.drop(columns=[
    "Accessibility_Score",
    "Accessibility_Category",
    "Improvement_Priority",
    "Location_ID",
    "Location_Name"
], errors="ignore")

"""**STEP 04 SCALE FEATURES**"""

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

"""**STEP 05 PCA (2 COMPONENTS)**"""

pca = PCA(n_components=2)

X_pca = pca.fit_transform(X_scaled)

print(pca.explained_variance_ratio_)

"""**STEP 06 PCA VISUALIZATION**"""

plt.figure(figsize=(8,6))

plt.scatter(
    X_pca[:,0],
    X_pca[:,1],
    alpha=0.7
)
plt.title("PCA Projection")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.show()

"""# **DBSCAN**

**STEP 07**
"""

dbscan = DBSCAN(
    eps=2,
    min_samples=8
)

db_labels = dbscan.fit_predict(X_scaled)
df["DBSCAN_Cluster"] = db_labels


# for eps in [1.5, 2.0, 2.5, 3.0, 3.5]:
#     db = DBSCAN(eps=eps, min_samples=5)
#     labels = db.fit_predict(X_scaled)

#     print(
#         "eps =", eps,
#         "Clusters =", len(set(labels)) - (1 if -1 in labels else 0),
#         "Noise =", list(labels).count(-1)
#     )

"""**STEP 08**"""

plt.figure(figsize=(8,6))

sns.scatterplot(
    x=X_pca[:,0],
    y=X_pca[:,1],
    hue=db_labels,
    palette="tab10"
)

plt.title("DBSCAN Clusters")

plt.show()

"""**STEP 09**"""

print(df["DBSCAN_Cluster"].value_counts())

"""# **EXPECTATION MAXIMIZATION (GAUSSIAN MIXTURE)**

**STEP 10**
"""

gmm = GaussianMixture(
    n_components=4,
    random_state=42
)

gmm_labels = gmm.fit_predict(X_scaled)
df["GMM_Cluster"] = gmm_labels

"""**STEP 11**"""

plt.figure(figsize=(8,6))

sns.scatterplot(
    x=X_pca[:,0],
    y=X_pca[:,1],
    hue=gmm_labels,
    palette="Set2"
)
plt.title("Gaussian Mixture Clusters")
plt.show()

"""**STEP 12**"""

print(df["GMM_Cluster"].value_counts())

"""# **MINIMUM SPANNING TREE (MST)**

**STEP 13 DISTANCE MATRIX**
"""

distance_matrix = squareform(
    pdist(X_scaled)
)

"""**STEP 14 CREATE MST**"""

mst = minimum_spanning_tree(
    distance_matrix
)

"""**STEP 15 CONVERT TO GRAPH**"""

graph = nx.from_scipy_sparse_array(mst)

"""**STEP 16 DRAW GRAPH**"""

plt.figure(figsize=(12,10))

pos = nx.spring_layout(
    graph,
    seed=42
)
nx.draw_networkx(
    graph,
    pos,
    node_size=15,
    with_labels=False
)
plt.title("Minimum Spanning Tree")
plt.show()

"""**COMPARE CLUSTERING RESULTS**"""

print("DBSCAN")
print(df["DBSCAN_Cluster"].value_counts())
print()
print("Gaussian Mixture")
print(df["GMM_Cluster"].value_counts())

"""**CLUSTER SUMMARY**"""

cluster_summary = df.groupby(
    "GMM_Cluster"
).mean(numeric_only=True)

cluster_summary

"""**SAVE DATASET**"""

df.to_csv(
    "clustered_accessibility_dataset.csv",
    index=False
)

from sklearn.metrics import silhouette_score

score = silhouette_score(
    X_scaled,
    gmm_labels
)

print("Silhouette Score:", round(score,3))