# -*- coding: utf-8 -*-
"""08_MODEL_OPTIMIZATION_EXPLAINABILITY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VB2eotY72xfhnSxDDRT-2k1h7PkYzF1O

**PART 01 IMPORT LIBRARIES**
"""

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import joblib

from sklearn.model_selection import (
    train_test_split,
    RandomizedSearchCV,
    cross_val_score
)

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    cohen_kappa_score
)

from sklearn.ensemble import (
    RandomForestRegressor,
    RandomForestClassifier
)

from xgboost import (
    XGBRegressor,
    XGBClassifier
)

from sklearn.preprocessing import LabelEncoder, StandardScaler

"""**PART 02 LOAD DATASET**"""

df = pd.read_csv("engineered_accessibility_dataset.csv")

"""**PART 03 ENCODE CLASSIFICATION TARGET**"""

encoder = LabelEncoder()

df["Accessibility_Category"] = encoder.fit_transform(
    df["Accessibility_Category"]
)

"""**PART 04 PREPARE FEATURES**"""

X_reg = df.drop(columns=[
    "Accessibility_Score",
    "Accessibility_Category",
    "Improvement_Priority",
    "Accessibility_Efficiency",
    "Location_ID",
    "Location_Name"
], errors="ignore")

y_reg = df["Accessibility_Score"]

# Classification
X_cls = X_reg.copy()
y_cls = df["Accessibility_Category"]

"""**PART 05 SCALE FEATURES**"""

scaler = StandardScaler()
X_reg_scaled = scaler.fit_transform(X_reg)
X_cls_scaled = scaler.transform(X_cls)

"""**STEP 06 TRAIN/TEST SPLIT**"""

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg_scaled,
    y_reg,
    test_size=0.20,
    random_state=42
)

#Classification
X_train_cls, X_test_cls, y_train_cls, y_test_cls = train_test_split(
    X_cls_scaled,
    y_cls,
    test_size=0.20,
    random_state=42,
    stratify=y_cls
)

"""# **SECTION 02 HYPERPARAMETER TUNING (REGRESSION)**

**STEP 01 RANDOM FOREST HYPERPARAMETER TUNING**
"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV

rf = RandomForestRegressor(random_state=42)

rf_params = {
    "n_estimators": [100, 200, 300, 500],
    "max_depth": [5, 10, 15, 20, None],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "max_features": ["sqrt", "log2"]
}

rf_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=rf_params,
    n_iter=20,
    scoring="r2",
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

rf_search.fit(X_train_reg, y_train_reg)

"""**STEP 02 BEST PARAMETERS**"""

print("Best Parameters:")
print(rf_search.best_params_)

print("\nBest CV R²:")
print(round(rf_search.best_score_, 3))

"""**STEP 03 EVALUATE BEST RANDOM FOREST**"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

best_rf = rf_search.best_estimator_

prediction = best_rf.predict(X_test_reg)

print("MAE :", round(mean_absolute_error(y_test_reg, prediction), 3))
print("RMSE :", round(np.sqrt(mean_squared_error(y_test_reg, prediction)), 3))
print("R² :", round(r2_score(y_test_reg, prediction), 3))

"""**STEP 04 XGBOSST GYPERPARAMETER TUNING**"""

from xgboost import XGBRegressor

xgb = XGBRegressor(
    random_state=42,
    objective="reg:squarederror"
)

xgb_params = {
    "n_estimators": [100, 200, 300, 500],
    "learning_rate": [0.01, 0.05, 0.1, 0.2],
    "max_depth": [3, 5, 7, 10],
    "subsample": [0.8, 1.0],
    "colsample_bytree": [0.8, 1.0]
}

xgb_search = RandomizedSearchCV(
    estimator=xgb,
    param_distributions=xgb_params,
    n_iter=20,
    scoring="r2",
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

xgb_search.fit(X_train_reg, y_train_reg)

"""**STEP 05 BEST PARAMETERS**"""

print("Best Parameters:")
print(xgb_search.best_params_)

print("\nBest CV R²:")
print(round(xgb_search.best_score_, 3))

"""**STEP 06 EVALUATE THE XGBOOST**"""

best_xgb = xgb_search.best_estimator_

prediction = best_xgb.predict(X_test_reg)

print("MAE :", round(mean_absolute_error(y_test_reg, prediction), 3))
print("RMSE :", round(np.sqrt(mean_squared_error(y_test_reg, prediction)), 3))
print("R² :", round(r2_score(y_test_reg, prediction), 3))

"""**STEP 07 COMPARE BOTH OPTIMIZED MODELS**"""

results = pd.DataFrame({
    "Model": ["Random Forest", "XGBoost"],
    "R²": [
        r2_score(y_test_reg, best_rf.predict(X_test_reg)),
        r2_score(y_test_reg, best_xgb.predict(X_test_reg))
    ],
    "MAE": [
        mean_absolute_error(y_test_reg, best_rf.predict(X_test_reg)),
        mean_absolute_error(y_test_reg, best_xgb.predict(X_test_reg))
    ],
    "RMSE": [
        np.sqrt(mean_squared_error(y_test_reg, best_rf.predict(X_test_reg))),
        np.sqrt(mean_squared_error(y_test_reg, best_xgb.predict(X_test_reg)))
    ]
})

results = results.sort_values(by="R²", ascending=False)
results

"""**STEP 08 SAVE THE BEST MODEL**"""

import joblib
best_model = best_xgb if results.iloc[0]["Model"] == "XGBoost" else best_rf
joblib.dump(best_model, "best_regression_model.pkl")

"""# **SECTION 02 HYPERPARAMETER TUNING (CLASSIFICATION)**

**STEP 01 RANDOM FOREST CLASSIFIER**
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV

rf_cls = RandomForestClassifier(random_state=42)

rf_params = {
    "n_estimators": [100, 200, 300, 500],
    "max_depth": [5, 10, 15, 20, None],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "max_features": ["sqrt", "log2"]
}

rf_search = RandomizedSearchCV(
    estimator=rf_cls,
    param_distributions=rf_params,
    n_iter=20,
    cv=5,
    scoring="accuracy",
    random_state=42,
    n_jobs=-1,
    verbose=1
)

rf_search.fit(X_train_cls, y_train_cls)

"""**STEP 02 BEST PARAMETERS**"""

print("Best Parameters:")
print(rf_search.best_params_)

print("\nBest CV Accuracy:")
print(round(rf_search.best_score_,3))

"""**STEP 03 EVALUATE BEST RANDOM FOREST**"""

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    cohen_kappa_score,
    confusion_matrix,
    classification_report
)

best_rf_cls = rf_search.best_estimator_

prediction = best_rf_cls.predict(X_test_cls)

print("Accuracy :", round(accuracy_score(y_test_cls,prediction),3))
print("Precision :", round(precision_score(y_test_cls,prediction,average="weighted"),3))
print("Recall :", round(recall_score(y_test_cls,prediction,average="weighted"),3))
print("F1 :", round(f1_score(y_test_cls,prediction,average="weighted"),3))
print("Kappa :", round(cohen_kappa_score(y_test_cls,prediction),3))

print("\nClassification Report\n")
print(classification_report(y_test_cls,prediction))

"""**STEP 04 CONFUSION MATRIX**"""

import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test_cls,prediction)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues"
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Random Forest")

plt.show()

"""**STEP 05 XBGOOST CLASSIFIER**"""

from xgboost import XGBClassifier

xgb_cls = XGBClassifier(
    random_state=42,
    eval_metric="mlogloss"
)

xgb_params = {
    "n_estimators":[100,200,300,500],
    "learning_rate":[0.01,0.05,0.1,0.2],
    "max_depth":[3,5,7,10],
    "subsample":[0.8,1.0],
    "colsample_bytree":[0.8,1.0]
}

xgb_search = RandomizedSearchCV(
    estimator=xgb_cls,
    param_distributions=xgb_params,
    n_iter=20,
    scoring="accuracy",
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

xgb_search.fit(X_train_cls,y_train_cls)

"""**STEP 06 BEST PARAMETERS**"""

print("Best Parameters:")
print(xgb_search.best_params_)

print("\nBest CV Accuracy:")
print(round(xgb_search.best_score_,3))

"""**STEP 07 EVALUATE THE XGBOOST**"""

best_xgb_cls = xgb_search.best_estimator_

prediction = best_xgb_cls.predict(X_test_cls)

print("Accuracy :", round(accuracy_score(y_test_cls,prediction),3))
print("Precision :", round(precision_score(y_test_cls,prediction,average="weighted"),3))
print("Recall :", round(recall_score(y_test_cls,prediction,average="weighted"),3))
print("F1 :", round(f1_score(y_test_cls,prediction,average="weighted"),3))
print("Kappa :", round(cohen_kappa_score(y_test_cls,prediction),3))

print("\nClassification Report\n")
print(classification_report(y_test_cls,prediction))

"""**STEP 08 CONFUSUION MATRIX**"""

cm = confusion_matrix(y_test_cls,prediction)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Greens"
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("XGBoost")

plt.show()

"""**STEP 09 COMPARE BEST MODELS**"""

comparison = pd.DataFrame({

    "Model":[
        "Random Forest",
        "XGBoost"
    ],

    "Accuracy":[
        accuracy_score(
            y_test_cls,
            best_rf_cls.predict(X_test_cls)
        ),
        accuracy_score(
            y_test_cls,
            best_xgb_cls.predict(X_test_cls)
        )
    ],

    "Precision":[
        precision_score(
            y_test_cls,
            best_rf_cls.predict(X_test_cls),
            average="weighted"
        ),
        precision_score(
            y_test_cls,
            best_xgb_cls.predict(X_test_cls),
            average="weighted"
        )
    ],

    "Recall":[
        recall_score(
            y_test_cls,
            best_rf_cls.predict(X_test_cls),
            average="weighted"
        ),
        recall_score(
            y_test_cls,
            best_xgb_cls.predict(X_test_cls),
            average="weighted"
        )
    ],

    "F1":[
        f1_score(
            y_test_cls,
            best_rf_cls.predict(X_test_cls),
            average="weighted"
        ),
        f1_score(
            y_test_cls,
            best_xgb_cls.predict(X_test_cls),
            average="weighted"
        )
    ],

    "Kappa":[
        cohen_kappa_score(
            y_test_cls,
            best_rf_cls.predict(X_test_cls)
        ),
        cohen_kappa_score(
            y_test_cls,
            best_xgb_cls.predict(X_test_cls)
        )
    ]

})

comparison.sort_values(
    by="Accuracy",
    ascending=False
)

"""**STEP 10 SAVE BEST CLASSIFIER**"""

import joblib

best_classifier = (
    best_xgb_cls
    if comparison.iloc[0]["Model"] == "XGBoost"
    else best_rf_cls
)

joblib.dump(
    best_classifier,
    "best_classification_model.pkl"
)

joblib.dump(
    encoder,
    "label_encoder.pkl"
)

joblib.dump(
    scaler,
    "scaler.pkl"
)

joblib.dump(
    list(X_reg.columns),
    "feature_columns.pkl"
)