# -*- coding: utf-8 -*-
"""08_Recommendation_Engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nA1QWWyAJ-45r-6TeydVzGTRUFqMUM1O

**STEP 01 LOAD DATASET**
"""

import pandas as pd
df = pd.read_csv("engineered_accessibility_dataset.csv")

"""**STEP 02 VERIFY COLUMNS**"""

print(df.columns.tolist())

"""**STEP 03 PREPARE FEATURES (REMOVE DATA LEAKAGE)**"""

X = df.drop(columns=[
    "Accessibility_Score",
    "Accessibility_Category",
    "Improvement_Priority",
    "Accessibility_Efficiency",
    "Location_ID",
    "Location_Name"
], errors="ignore")

y = df["Accessibility_Score"]

"""**STEP 04 TRAIN-TEST SPLIT**"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

"""**STEP 05 TRAIN THE BEST REGRESSION MODEL(XGBOOST)**"""

from xgboost import XGBRegressor

xgb = XGBRegressor(
    random_state=42,
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1
)
xgb.fit(X_train, y_train)

"""**STEP 06 EVALUATE THE MODEL**"""

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import numpy as np

prediction = xgb.predict(X_test)

mae = mean_absolute_error(y_test, prediction)
rmse = np.sqrt(mean_squared_error(y_test, prediction))
r2 = r2_score(y_test, prediction)

print("MAE :", round(mae,3))
print("RMSE :", round(rmse,3))
print("R² :", round(r2,3))

"""**STEP 07 SAVE THE NEW MODEL**"""

import joblib

joblib.dump(
    xgb,
    "best_regression_model.pkl"
)

"""**STEP 08 CHECK THE FEATURES USED BY THE MODEL**"""

print(xgb.feature_names_in_)

"""**STEP 09 LOAD THE MODEL IN RECOMMENDATION NOTEBOOK**"""

import joblib

regression_model = joblib.load("best_regression_model.pkl")
classification_model = joblib.load("best_classification_model.pkl")

"""**STEP 10 PREPARE PREDICTION DATA CORRECTLY**"""

prediction_data = df[
    regression_model.feature_names_in_
].copy()

"""**STEP 11 MAKE PREDICTIONS**"""

df["Predicted_Accessibility"] = regression_model.predict(
    prediction_data
)

"""**STEP 12 CLASSIFICATION PREDICTION**"""

classification_data = df[
    classification_model.feature_names_in_
].copy()

# Predict categories
df["Predicted_Category"] = classification_model.predict(
    classification_data
)

"""**STEP 13 CONVERT CATEGORY NUMBERS BACK TO LABELS**"""

from sklearn.preprocessing import LabelEncoder

# Initialize and fit the encoder (assuming it was fit on the original Accessibility_Category)
encoder = LabelEncoder()
encoder.fit(df["Accessibility_Category"])

df["Predicted_Category"] = encoder.inverse_transform(
    df["Predicted_Category"]
)

"""**STEP 14 DISPLAY FINAL RESULTS**"""

df[[
    "Location_Name",
    "Predicted_Accessibility",
    "Predicted_Category"
]].head(10)